"""dual QR codes, service time window, rejection fields

Revision ID: efcac4a8ac76
Revises: 70fb2f583bcb
Create Date: 2026-09-24 11:58:33.654466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efcac4a8ac76'
down_revision: Union[str, None] = '70fb2f583bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Bottles are switching from one QR code to two (refund + manufacturing).
    # Existing bottles/returns/payments are dev-only test fixtures with no
    # real-world data to preserve, so they're cleared here rather than
    # migrated column-by-column.
    op.execute("DELETE FROM payments")
    op.execute("DELETE FROM return_transactions")
    op.execute("DELETE FROM bottles")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bottles', sa.Column('refund_qr_code', sa.String(length=64), nullable=False))
    op.add_column('bottles', sa.Column('manufacturing_qr_code', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_bottles_qr_code'), table_name='bottles')
    op.create_index(op.f('ix_bottles_manufacturing_qr_code'), 'bottles', ['manufacturing_qr_code'], unique=True)
    op.create_index(op.f('ix_bottles_refund_qr_code'), 'bottles', ['refund_qr_code'], unique=True)
    op.drop_column('bottles', 'qr_code')
    op.add_column('payments', sa.Column('customer_identifier', sa.String(length=120), nullable=True))

    rejection_reason_enum = sa.Enum(
        'REFUND_QR_DAMAGED', 'MANUFACTURING_QR_DAMAGED', 'REFUND_QR_INVALID', 'MANUFACTURING_QR_INVALID',
        'QR_ALREADY_USED', 'BOTTLE_PHYSICALLY_DAMAGED', 'BOTTLE_BROKEN_CRACKED', 'BOTTLE_TAMPERED',
        'BOTTLE_NOT_ELIGIBLE', 'OTHER', name='rejection_reason',
    )
    rejection_reason_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('return_transactions', sa.Column('rejection_reason', rejection_reason_enum, nullable=True))
    op.add_column('return_transactions', sa.Column('evidence_image_path', sa.String(length=255), nullable=True))
    op.add_column('return_transactions', sa.Column('remarks', sa.Text(), nullable=True))
    op.alter_column('return_transactions', 'bottle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('shops', sa.Column('service_start_time', sa.Time(), nullable=True))
    op.add_column('shops', sa.Column('service_end_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'service_end_time')
    op.drop_column('shops', 'service_start_time')
    op.alter_column('return_transactions', 'bottle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('return_transactions', 'remarks')
    op.drop_column('return_transactions', 'evidence_image_path')
    op.drop_column('return_transactions', 'rejection_reason')
    sa.Enum(name='rejection_reason').drop(op.get_bind(), checkfirst=True)
    op.drop_column('payments', 'customer_identifier')
    op.add_column('bottles', sa.Column('qr_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_bottles_refund_qr_code'), table_name='bottles')
    op.drop_index(op.f('ix_bottles_manufacturing_qr_code'), table_name='bottles')
    op.create_index(op.f('ix_bottles_qr_code'), 'bottles', ['qr_code'], unique=True)
    op.drop_column('bottles', 'manufacturing_qr_code')
    op.drop_column('bottles', 'refund_qr_code')
    # ### end Alembic commands ###
